### ISSUE TITLE
Add space for text on about page

### ISSUE THREAD

**Issue by twiecki** [pymc-labs/pymc-labs.github.io#19]
Looks a bit dense:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/674200/97356208-38161900-1898-11eb-9811-dc4ec2c76e34.png">

**Comment by ericmjl** [comment]
What browser, screen resolution, and OS did you take this screenshot on? 

On my 12" MacBook:

![image](https://user-images.githubusercontent.com/2631566/97379243-ba074180-189a-11eb-94f7-f1d79c525bb3.png)

**Comment by twiecki** [comment]
I just retried and it looks correct now:
![Uploading image.png…]()

This is firefox.
