### ISSUE TITLE
Make it so that www.pymc-labs.io stays in the address bar

### ISSUE THREAD

**Issue by twiecki** [pymc-labs/pymc-labs.github.io#27]
Currently going to `pymc-labs.io` redirects to https://pymc-labs.github.io//, would be better if it just always stayed on that URL.

**Comment by OriolAbril** [comment]
This seems to be the guide to do that https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by ericmjl** [comment]
I think @canyon289 has solved this issue.
