### ISSUE TITLE
Nav-bar on "what we do" does not show correctly selected sub-header

### ISSUE THREAD

**Issue by twiecki** [pymc-labs/pymc-labs.github.io#31]
When I click on the second item it jumps to the correct text position, but the blue selector is still at the top.
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/674200/97602097-315be300-1a0b-11eb-8c50-1d5127eb4d2b.png">

**Comment by ericmjl** [comment]
Not sure how that happened for you; it's working fine on Safari. Anybody else experiencing the same problems?

Check to make sure you haven't ever so slightly shifted your scroll position on the page. Scrollspy is sensitive to that.

**Comment by drbenvincent** [comment]
@ericmjl I think this issue is moot now that we've removed the navbar?

**Comment by twiecki** [comment]
Yes.
